/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'landandplot';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CLUSTER_ICON = 'assets/cluster_icon.png';
  static const String GPS = 'assets/icons/gps.png';
  static const String LADAKH_2818861_1280 = 'assets/images/ladakh-2818861_1280.jpg';
  static const String LANDSCAPE_5298395_1280 = 'assets/images/landscape-5298395_1280.jpg';
  static const String TEMPLE_3181803_1280 = 'assets/images/temple-3181803_1280.jpg';
  static const String PROPERTIES = 'assets/properties.json';
  static const String WHATSAPP_LOGO = 'assets/whatsapp_logo.png';
}
