// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrccvHYGMAEXs_Z78Z3uQnZZCLNsPbh8',
    appId: '1:552375181319:web:1787dc1cad9da0ff360aa2',
    messagingSenderId: '552375181319',
    projectId: 'landandplot-1009',
    authDomain: 'landandplot-1009.firebaseapp.com',
    databaseURL: 'https://landandplot-1009.firebaseio.com',
    storageBucket: 'landandplot-1009.appspot.com',
    measurementId: 'G-HZKJFFVEEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASbumO_6lhs3SNKCx1UOs7DgmURjOJHDY',
    appId: '1:552375181319:android:95b1e51755933e60360aa2',
    messagingSenderId: '552375181319',
    projectId: 'landandplot-1009',
    databaseURL: 'https://landandplot-1009.firebaseio.com',
    storageBucket: 'landandplot-1009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0C2CCzmHSRBeQRwW9zD5qmzqz0VG56gE',
    appId: '1:552375181319:ios:83e134bed542e9de360aa2',
    messagingSenderId: '552375181319',
    projectId: 'landandplot-1009',
    databaseURL: 'https://landandplot-1009.firebaseio.com',
    storageBucket: 'landandplot-1009.appspot.com',
    androidClientId: '552375181319-lno2u3g1lrs8fm9o02vu2oj8j79oq81g.apps.googleusercontent.com',
    iosClientId: '552375181319-jrce03vleoaguhppdsnpn5r8oh8vjs1q.apps.googleusercontent.com',
    iosBundleId: 'com.mmsoft.landandplot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0C2CCzmHSRBeQRwW9zD5qmzqz0VG56gE',
    appId: '1:552375181319:ios:5669d1c065b7ffa3360aa2',
    messagingSenderId: '552375181319',
    projectId: 'landandplot-1009',
    databaseURL: 'https://landandplot-1009.firebaseio.com',
    storageBucket: 'landandplot-1009.appspot.com',
    androidClientId: '552375181319-lno2u3g1lrs8fm9o02vu2oj8j79oq81g.apps.googleusercontent.com',
    iosClientId: '552375181319-r9uq8ark4cobg4ims1jkt77c5ol89ngs.apps.googleusercontent.com',
    iosBundleId: 'com.mmsoft.landandplot.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQrccvHYGMAEXs_Z78Z3uQnZZCLNsPbh8',
    appId: '1:552375181319:web:477524329a2ba5ab360aa2',
    messagingSenderId: '552375181319',
    projectId: 'landandplot-1009',
    authDomain: 'landandplot-1009.firebaseapp.com',
    databaseURL: 'https://landandplot-1009.firebaseio.com',
    storageBucket: 'landandplot-1009.appspot.com',
    measurementId: 'G-BD5LLP0D4G',
  );
}